version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=nilai_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: . 
    container_name: uts
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=nilai_db
      - DB_USER=postgres
      - DB_PASS=admin123
      - DB_PORT=5432
      - DATA_NILAI=85,90,78,92,88,95,80,100,150
    volumes:
      - .:/app
    command: sh -c "sleep 10 && python uts.py"

volumes:
  postgres_data: